name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Send Notification on Success
        if: ${{ success() }}
        uses: dawidd6/action-send-mail@v3
        COMMITTER=$(echo "${{ steps.commit-info.outputs.committer }}")
        COMMIT_STATUS=$(echo "${{ steps.commit-info.outputs.commit_status }}")
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'EC2 Deployment Succeeded for commit $COMMITTER'
          body: 'The deployment to EC2 was successful.'
          to: saumil.jain@technostacks.com, saumiljain375@gmail.com  # Add developer emails

      - name: Send Notification on Failure
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v3
        COMMITTER=$(echo "${{ steps.commit-info.outputs.committer }}")
        COMMIT_STATUS=$(echo "${{ steps.commit-info.outputs.commit_status }}")
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'EC2 Deployment Failed for commit $COMMITTER'
          body: 'The deployment to EC2 has failed.'
          to: saumil.jain@technostacks.com, saumiljain375@gmail.com  # Add developer emails
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo service apache2 restart
            
            
