name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Get last commit information
        id: commit-info
        run: |
          COMMITTER=$(git log -1 --pretty=format:'%an')
          COMMIT_STATUS=$(git log -1 --pretty=format:'%B' | grep -i 'fix\|bug\|error' | wc -l)
          echo "::set-output name=committer::$COMMITTER"
          echo "::set-output name=commit_status::$COMMIT_STATUS"

      - name: Send Notification on Success
        if: success()
        run: |
          COMMITTER=$(echo "${{ steps.commit-info.outputs.committer }}")
          echo "Deployment to EC2 succeeded for commit $COMMITTER. Sending notification..."
          echo "The deployment to EC2 was successful." | mail -s "EC2 Deployment Succeeded for commit $COMMITTER" -a "From: Your Name <${{ secrets.EMAIL_USERNAME }}>" saumil.jain@technostacks.com saumiljain375@gmail.com

      - name: Send Notification on Failure
        if: failure()
        run: |
          COMMITTER=$(echo "${{ steps.commit-info.outputs.committer }}")
          echo "Deployment to EC2 failed for commit $COMMITTER. Sending notification..."
          echo "The deployment to EC2 has failed." | mail -s "EC2 Deployment Failed for commit $COMMITTER" -a "From: Your Name <${{ secrets.EMAIL_USERNAME }}>" saumil.jain@technostacks.com saumiljain375@gmail.com

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo service apache2 restart
